config/routes.rb
Rails.application.routes.draw do
  resources :posts, only: [:index, :new, :create]
  root 'posts#index'
  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale
 
	def set_locale
		if cookies[:post_locale] && I18n.available_locales.include?(cookies[:post_locale].to_sym)
    	l = cookies[:post_locale].to_sym
    else
    	l = I18n.default_locale
    	cookies.permanent[:post_locale] = l
	  end
	  I18n.locale = l
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		if @post.save
			redirect_to posts_url
		else
			render :new
		end
	end

	private

	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
	def change_locale
    l = params[:locale].to_s.strip.to_sym
    l = I18n.default_locale unless I18n.available_locales.include?(l)
    cookies.permanent[:post_locale] = l
    redirect_to request.referer || root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railshw</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <%= link_to t('menu.all_posts'), root_path, class: 'navbar-brand' %>
      </div>
 
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to t('menu.new_post'), new_post_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          <%= t('menu.languages.lang') %>
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu" role="menu">
          <li>
            <%= link_to t('menu.languages.en'), change_locale_path(:en) %>
          </li>
          <li>
            <%= link_to t('menu.languages.vi'), change_locale_path(:vi) %>
          </li>
        </ul>
      </li>
    </ul>

    </div>
  </div>
 
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
    <% end %>
 
    <div class="page-header">
      <h1><%= yield :page_header %></h1>
    </div>
 
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/index.html.erb
<h1> <%= t('posts.index.all_post') %> </h1>
<% @posts.each do |post| %>
	<h2> <%= post.title %> </h2>
	<p> <%= post.body %> </p>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<%= f.label :title %>
	<%= f.text_field  :title %><br>
	<%= f.label :body %>
	<%= f.text_area  :body %><br>
	<%= f.submit %>
<% end %>